openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: An API for managing a contact book that allows users to create, update, delete, and search for contacts.
tags:
  - name: Contacts
    description: Endpoints for managing contacts.
  - name: Auth
    description: Endpoints for user authentication.
servers:
  - url: https://nodejs-hw-mongodb-92jy.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get: 
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd.yaml
  /auth/get-oauth-url:
    post:
      $ref: ../swagger/paths/auth/get-oauth-url.yaml
  /auth/confirm-google:
    post:
      $ref: ../swagger/paths/auth/confirm-google.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
